#!/usr/bin/python3.13
import sys as s
import os

# Path of 'dirprogramming' file
dir_prog = "/home/salah/Documents/.programming/Bash/Developer/Project/Command/dirprogramming"

# Variables
option = "-fd"
options = ['f', 'd', 'fd', 'df']
if s.argv[1][:1] == '-' and s.argv[1][1:] in options:
    option = s.argv[1]
    lang = s.argv[2]
    short_lang = s.argv[3] if len(s.argv) >= 4 else lang.lower()
    style = s.argv[4] if len(s.argv) >= 5 else '1'
elif s.argv[1][:1] == '-' and not s.argv[1][1:] in options:
    print("Unkown Option")
    s.exit()
else:
    lang = s.argv[1]
    short_lang = s.argv[2] if len(s.argv) >= 3 else lang.lower()
    style = s.argv[3] if len(s.argv) >= 4 else '1'

# Read 'dirprogramming' file
data = []
with open(dir_prog, 'r') as file:
    for word in file.readlines():
        data.append(word[0:-1])
    file.close()

# Add information about this language to the 'dirprogramming' file
info = f'''elif [ "$lang" = "{short_lang}" ]; then
   cd {lang}
   navigate
fi'''

# Insert the information of this language to the 'data' list variable
data = data[0:-1]
for item in info.split("\n"):
    data.append(item)

# Now writing that 'data' list to the 'dirprogramming' file
if option[:1] == '-' and  (option[-1] == 'f' or option[1:] == 'fd' or option[1:] == 'df'):
    with open(dir_prog, 'w') as file:
        for word in "\n".join(data):
            file.write(word)
        file.close()

# Directory structure
dir_structure = {
    '1': {
        f"{lang}": [f"{lang}/Developer", f"{lang}/Project", f"{lang}/Virtual\\ Environment", f"{lang}/Web"],
        "Developer": [f"{lang}/Developer/Project", f"{lang}/Developer/Quick", f"{lang}/Developer/Tutorial"],
        "Developer/Tutorial": [f"{lang}/Developer/Tutorial/Basic", f"{lang}/Developer/Tutorial/Learn"]
    },
    '2': {
        f"{lang}": [f"{lang}/Developer", f"{lang}/Project" f"{lang}/Web"],
        "Developer": [f"{lang}/Developer/Project", f"{lang}/Developer/Quick", f"{lang}/Developer/Tutorial", f"{lang}/Developer/Package"],
        "Developer/Project": [f"{lang}/Developer/Project/Command"],
        "Developer/Tutorial": [f"{lang}/Developer/Tutorial/Basic", f"{lang}/Developer/Tutorial/Learn"]
    }
}

# Create directories and subdirectories for this language
if option[:1] == '-' and  (option[-1] == 'd' or option[1:] == 'df' or option[1:] == 'fd'):
    for parent in dir_structure[style].keys():
        for child in dir_structure[style][parent]:
            os.system(f"mkdir -p {child}")
