#!/usr/bin/python3.13
import sys as s
import os

def isSymbol(string):
    return True if not(string.isalpha()) and not(string.isdigit()) else False

def getOption(args):
    options = ['d', 'f']
    option = ""
    list_option = []
    for arg in args:
        for g in arg[1:]:
            if g in options and arg[0] == '-':
                option += g if option.count(g) == 0 else ""
        list_option.append(option) if not(option == "") else list_option
        option = ""
    return list_option

options = getOption(s.argv[1:]) if len(getOption(s.argv[1:])) > 0 else 'df'
files = [file for file in s.argv[1:] for char in file if ((char == file[0]) and not((char.isdigit()) or isSymbol(char)))]
styles = [arg for arg in s.argv[1:] if arg.isdigit()]

file_name = files[0]
short_name = files[1] if len(files) > 1 else file_name.lower()

style = styles[0] if len(styles) > 0 else '1'

# Path to 'dirprogramming' File
dir_prog = "/home/salah/Documents/.programming/Bash/Developer/Project/Command/dirprogramming"

# Read 'dirprogramming' File
data = []
with open(dir_prog, 'r') as file:
    for word in file.readlines():
        data.append(word[0:-1])
    file.close()

# Information to Add to 'dirprogramming' File
info = f'''elif [ "$lang" = "{short_name}" ]; then
   cd {file_name}
   navigate
fi'''

# Insert the Information to 'dirprogramming' File
data = data[0:-1]
for item in info.split("\n"):
    data.append(item)

# Structure to Build Directory
dir_structure = {
    '1': {
        f"{file_name}": [f"{file_name}/Developer", f"{file_name}/Project", f"{file_name}/Virtual\\ Environment", f"{file_name}/Web"],
        "Developer": [f"{file_name}/Developer/Project", f"{file_name}/Developer/Quick", f"{file_name}/Developer/Tutorial"],
        "Developer/Tutorial": [f"{file_name}/Developer/Tutorial/Basic", f"{file_name}/Developer/Tutorial/Learn"]
    },
    '2': {
        f"{file_name}": [f"{file_name}/Developer", f"{file_name}/Project" f"{file_name}/Web"],
        "Developer": [f"{file_name}/Developer/Project", f"{file_name}/Developer/Quick", f"{file_name}/Developer/Tutorial", f"{file_name}/Developer/Package"],
        "Developer/Project": [f"{file_name}/Developer/Project/Command"],
        "Developer/Tutorial": [f"{file_name}/Developer/Tutorial/Basic", f"{file_name}/Developer/Tutorial/Learn"]
    }
}

# Display
os.chdir("/home/salah/Documents/.programming")
for option in options:
    if 'f' in option:
        with open(dir_prog, 'w') as file:
            for word in "\n".join(data):
                file.write(word)
            file.close()
    if 'd' in option:
        for parent in dir_structure[structure].keys():
            for child in dir_structure[structure][parent]:
                os.system(f"mkdir -p {child}")
