#!/usr/bin/python3.13
import os
import subprocess as subp

path = "/home/salah/Documents/.programming"
command_path = "Developer/Project/Command"

for dir in os.listdir(path):
	if os.path.exists(f'{path}/{dir}/{command_path}') and not(os.listdir(f'{path}/{dir}/{command_path}') == []):
		print(f"{dir}:")
		return_code = subp.run(["ls", path+"/"+dir+"/"+command_path], capture_output=True).stdout.decode()
		print(return_code[:-1].split("\n"))
